### ISSUE TITLE
static binary build steps

### ISSUE THREAD

**Issue by rsubr** [philipgloyne/apachebench-for-multi-url#5]
@philipgloyne thanks for this project, it was exactly what I needed for one of my testing requirements. It will be great if you can add the below steps to the documentation on how to create a static binary which can be run on any Linux system.

```bash
$ git checkout https://github.com/philipgloyne/apachebench-for-multi-url.git
$ docker run -ti --rm -v `pwd`/apachebench-for-multi-url:/build alpine /bin/sh
$ apk add build-base apr-util-dev apache2-dev openssl-libs-static
$ cd /build
$ gcc -I /usr/include/apr-1 -I /usr/include/apache2 -I /usr/include/openssl ab.c -o ab -lm -lapr-1 -laprutil-1 -lssl -lcrypto -ldl -static
```

Static x64 binary: [ab.gz](https://github.com/philipgloyne/apachebench-for-multi-url/files/6458731/ab.gz)

**Comment by philipgloyne** [comment]
done, thanks
